### PR TITLE
Changed RY bio and added profile picture.

### PR DESCRIPTION
**Pull request by rubyyee**

### CODE REVIEW

**Comment by rubyyee** [comment]
Hey Clark, thanks! I just added quotations around that line and pushed it back to my fork. Is the change visible to you?

**Comment by richardsc** [comment]
Looks good! I'll merge.

**Comment by richardsc** [comment]
Success! 😄 

https://daloceandynamicsgroup.github.io/member/rubyyee/

**Comment by rubyyee** [comment]
Looks great!!

**Pull request merged**
